#!/bin/bash
#
# This runs rfclint to check for duplicate words
# in an XML file.
#
if [ "$#" -eq 3 ] && [ "z$2" == "z-o" ] ; then ofparm="-o $3" ;
elif [ "$#" -eq 2 ] ; then ofparm="-o $2" ;
elif [ "$#" -eq 1 ] ; then ofparm="" ;
else
	echo "$0: usage: $0 infile [[ -o ] ofparm]"
	exit 1
fi
if [ ! -f $1 ]; then
	echo "$0: $1: not found"
	exit 1
fi
rfclint $1 -n --no-spell --no-xml --no-abnf --no-network $ofparm
exit $?
